server:
  port: 9901
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planet_project?useSSL=false&serverTimezone=UTC
    username: root
    password: qwe123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



  messages:
    basename: messages.exception
  jackson:
      default-property-inclusion: non_null
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 0
          time-between-eviction-runs: 10s
mybatis:
  configuration:
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    mapUnderscoreToCamelCase: true
  typeAliasesPackage: app.planet.domain.model
  mapperLocations: classpath:/mapper/*.xml

planet:
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t6UNSP2zNCDZ89r53Xx
    access-key-secret: iib2rNO3SFprXrXvORppwEqE2VBJDE
    bucket-name: planet-file

